import type { Product } from "@/lib/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "gorra-snapback-classic-negra",
    name: "Gorra Snapback Classic Negra",
    description:
      "Gorra snapback de perfil alto, visera plana y ajuste trasero regulable. Ideal para uso diario.",
    price: 18000,
    category: "gorras",
    audience: "unisex",
    ageGroup: "adulto",
    sizes: ["Único"],
    stock: 24,
    featured: true,
  },
  {
    id: "2",
    slug: "gorra-trucker-vintage",
    name: "Gorra Trucker Vintage",
    description:
      "Frente de gamuza y dorso de malla transpirable. Un clásico que nunca pasa de moda.",
    price: 16500,
    category: "gorras",
    audience: "hombre",
    ageGroup: "adulto",
    sizes: ["Único"],
    stock: 15,
    featured: true,
  },
  {
    id: "3",
    slug: "gorra-dad-hat-bordada",
    name: "Gorra Dad Hat Bordada",
    description:
      "Perfil bajo, curva suave y bordado en el frente. Ajuste con hebilla metálica.",
    price: 17000,
    category: "gorras",
    audience: "mujer",
    ageGroup: "adulto",
    sizes: ["Único"],
    stock: 0,
    featured: false,
  },
  {
    id: "4",
    slug: "gorra-fitted-street",
    name: "Gorra Fitted Street",
    description: "Calce cerrado sin ajuste, estructura reforzada, para un look prolijo.",
    price: 19500,
    category: "gorras",
    audience: "hombre",
    ageGroup: "adulto",
    sizes: ["S/M", "L/XL"],
    stock: 10,
    featured: false,
  },
  {
    id: "5",
    slug: "sombrero-panama-clasico",
    name: "Sombrero Panamá Clásico",
    description: "Tejido fino tipo panamá, cinta grosgrain y ala media. Fresco para el verano.",
    price: 32000,
    category: "sombreros",
    audience: "unisex",
    ageGroup: "adulto",
    sizes: ["56", "58", "60"],
    stock: 8,
    featured: true,
  },
  {
    id: "6",
    slug: "sombrero-fedora-cuero",
    name: "Sombrero Fedora de Cuero",
    description: "Fedora en cuero genuino, ala corta y cinta a tono. Un statement piece.",
    price: 45000,
    category: "sombreros",
    audience: "hombre",
    ageGroup: "adulto",
    sizes: ["56", "58", "60"],
    stock: 5,
    featured: true,
  },
  {
    id: "7",
    slug: "sombrero-australiano",
    name: "Sombrero Australiano",
    description: "Ala ancha resistente al agua, ideal para trabajo de campo o aventura.",
    price: 38000,
    category: "sombreros",
    audience: "unisex",
    ageGroup: "adulto",
    sizes: ["58", "60", "62"],
    stock: 12,
    featured: false,
  },
  {
    id: "8",
    slug: "sombrero-bucket-hat",
    name: "Bucket Hat",
    description: "Reversible, liviano y plegable. El favorito para los días de sol.",
    price: 14000,
    category: "sombreros",
    audience: "mujer",
    ageGroup: "adulto",
    sizes: ["Único"],
    stock: 20,
    featured: false,
  },
  {
    id: "9",
    slug: "boina-clasica-de-pano",
    name: "Boina Clásica de Paño",
    description:
      "Boina tradicional de paño, forrada, en calce ajustable. Un clásico de toda la vida.",
    price: 15500,
    category: "boinas",
    audience: "unisex",
    ageGroup: "adulto",
    sizes: ["Único"],
    stock: 18,
    featured: true,
  },
  {
    id: "10",
    slug: "boina-infantil",
    name: "Boina Infantil",
    description: "Versión chica de nuestra boina clásica, para los más pequeños de la familia.",
    price: 9500,
    category: "boinas",
    audience: "unisex",
    ageGroup: "nino",
    sizes: ["Único"],
    stock: 14,
    featured: false,
  },
];
